database:
  decoy_string: "DECOY_"
  decoy_string_position: "prefix"
  missing_decoy_action: "warn"

fasta:
    location: "ftp.peptideatlas.org/distro/fasta"

mzml:
    location: "ftp.peptideatlas.org/distro/mzML"

search_engines:
    - "msgfplus"
    - "xtandem"
#    - "comet"
#    - "myrimatch"

lc:
    peak_width: '120'

precursor:
    tolerance: '20'
    units: 'ppm'

fragment:
    tolerance: '20'
    units: 'ppm'

digestion:
    enzyme: "Trypsin/P"
    missed_cleavages: "3"

modifications:
    fixed: "\"Carbamidomethyl (C)\""
    variable: ""

protein:
    fdr: "0.95"

peptide:
    fdr: "0.01"

singularity:
    default: "shub://mafreitas/singularity-openms:latest"

debug: "0"
